### ISSUE TITLE
scm-source.json is missing

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando/exhibitor-appliance#16]
After deployment pierone.stups.zalan.do/acid/exhibitor:0.1-SNAPSHOT into our AWS account YourTurn started to raise violations with type "SCM_SOURCE_JSON_MISSING".

Could you please add scm-source.json as it is described in http://stups.readthedocs.org/en/latest/user-guide/application-development.html#scm-source-json ?

**Comment by drummerwolli** [comment]
this is not the most recent image. please use the current one from the OS registry:

```
registry.opensource.zalan.do/acid/exhibitor:3.4-p4
```

you can find out the latest one with this command:

```
$ curl -s https://registry.opensource.zalan.do/teams/acid/artifacts/exhibitor/tags | jq "sort_by(.created)"
```

**Comment by dmitrykrivaltsevich** [comment]
We deployed registry.opensource.zalan.do/acid/exhibitor:3.4-p4,
YourTurn still reports "SCM_SOURCE_JSON_MISSING"

**Comment by hjacobs** [comment]
Yes, the `scm-source.json` is indeed missing or invalid, check https://registry.opensource.zalan.do/teams/acid/artifacts/exhibitor/tags/3.4-p4/scm-source

**Comment by hjacobs** [comment]
proof:

```
docker run -it --entrypoint /bin/ls registry.opensource.zalan.do/acid/exhibitor:3.4-p4 /scm-source.json
/bin/ls: cannot access /scm-source.json: No such file or directory
```

**Comment by drummerwolli** [comment]
done with the new image: https://registry.opensource.zalan.do/teams/acid/artifacts/exhibitor/tags/3.4-p5/scm-source

please close

**Comment by dmitrykrivaltsevich** [comment]
Thank you!
