### ISSUE TITLE
authorization

### ISSUE THREAD

**Issue by drummerwolli** [zalando/exhibitor-appliance#7]
did anyone already look into this? can we easily set this up for this appliance?

https://github.com/Netflix/exhibitor/wiki/Authentication-Setup

**Comment by valgog** [comment]
One of the 'solutions' of this problem would be to build a tunnel with piu. Maybe documentingin the README of how to build a tunnel, would be enough.

But solving a problem of Jetty configuration to use STUPS OAuth infrastructure is an interesting task by itself.

**Comment by drummerwolli** [comment]
we've been using for half a year now the https://github.com/zalando-stups/ssh-tunnels solution. will add a link to the Readme for this. this can be closed ...
